[databases]
* = host=postgres port=5432 auth_user=dana_user

[pgbouncer]
# Connection settings
listen_addr = *
listen_port = 6432
auth_type = plain
auth_file = /etc/pgbouncer/userlist.txt

# Session / Connection management
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 50
reserve_pool_size = 25
reserve_pool_timeout = 5

# Logging & Management
admin_users = dana_user
stats_users = dana_user
log_connections = 0
log_disconnections = 0
log_pooler_errors = 1
